[package]
name = "ordnl"
version = "1.0.2"
authors = ["Kirk Louie Guinto <kirklouieguinto@gmail.com>"]
edition = "2018"
description = "A Rust library for formatting ordinal numbers"
homepage = "https://github.com/kguinto/ordnl"
license = "MIT"

[dependencies]
